development:
  store: example.myshopify.com
  password: add-password-in-config
  theme_id: "live"
  bucket_size: 40
  refill_rate: 2
  ignore_files:
    - "*.swp"
    - "*~"
    - "config/settings_data.json"




