development:
  store: neighborlys.myshopify.com
  password: 145bc941c35259aae82a5c7b8072ba99
  theme_id: "live"
  bucket_size: 40
  refill_rate: 2
  ignore_files:
    - "*.swp"
    - "*~"
    - "config/settings_data.json"







